---
- name: install tree git apache
  hosts: all
  become: yes
  tasks:
    - name: install all of them
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
      when: ansible_facts['os_family']=="Debian"
    - name: enable and start
      ansible.builtin.systemd_service:
        name: "{{ package_name }}"
        enabled: yes
        state: started