---
- name: install apache and php
  hosts: webserver
  become: yes
  tasks:
    - name: fail on other os family other thah Debian and Redhat
      ansible.builtin.fail:
        msg: only work on debian and redhat
      when: ansible_facts['os_family'] != 'Debian' and ansible_facts['os_family'] != 'Redhat'
    - name: install apache
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present
      notify:
        - enable and start apache
    - name: install php info
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present
      notify:
        - restart apache
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: 
        - restart apache
  handlers:
    - name: enable and start apache
      ansible.builtin.service:
        name: "{{ package }}"
        enabled: yes
        state: started
    - name: restart apache
      ansible.builtin.service:
        name: "{{ package }}"
        state: restarted